spring:
  application:
    name: spring-ai-smart-qa
  ai:
    alibaba:
      dashscope:
        api-key: ${DASHSCOPE_API_KEY}
        chat:
          model: ${DASHSCOPE_MODEL:qwen-turbo} # ??????
          temperature: 0.7
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY}
    openai:
      api-key: dummy-key

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true